### ISSUE TITLE
Overriding Instagram CSP worker-src

### ISSUE THREAD

**Issue by fattynoparents** [Rufflewind/chrome_cspmod#3]
Hi I tried using your extension because I faced the necessity to override Instagram worker-src. 

I have an extension that downloads Instagram media as a ZIP archive, and now Instagram has apparently changed smth and I am unable to access Worker. 

The error is: "Refused to create a worker from 'blob:https://www.instagram.com/---' because it violates the following Content Security Policy directive: "worker-src 'self' https://www.instagram.com"

So I added this to the Options of your extension: 
["https://instagram\\.com", [
        ["worker-src", "worker-src blob:"]
    ]]
]

But the CSP is not changed for some reason. Can you help me with this? 
Thanks.

**Comment by Rufflewind** [comment]
Did you mean to override `https://instagram\.com` or `https://www\.instagram\.com` ?

**Comment by fattynoparents** [comment]
Thanks, you are right, that solved the issue.
