### ISSUE TITLE
Extension Does Not Seem to Disable CSP for Certain Sites

### ISSUE THREAD

**Issue by lunethefirst** [Rufflewind/chrome_cspmod#4]
Hey, happy holidays!

I was testing this on Steam (steampowered.com) and noticed that I was unable to disable CSP for loading scripts.
I used a few variations of the URL and using the background page/debugger, it looked like the extension was indeed running but I still couldn't get "script-src" to allow URLs from my domain.

I found a workaround using a different extension but wanted to give you a heads up.
I'll try and add some more details later.

**Comment by Rufflewind** [comment]
1. What page (URL) did you visit?
2. Can you show me the rule you tried?

---

Here's the rule I tried:

```js
[
    ["https://steampowered\\.com", [
       ["script-src", "script-src https://cdn.jsdelivr.net"]
    ]]
]
```

Then, I visited https://steampowered.com in Chromium, hit Ctrl+Shift+J, and pasted this:

```js
var script = document.createElement("script");
script.src = "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js";
document.documentElement.appendChild(script);
```

And no errors appeared.  In contrast, if I remove the rule, the script would fail to load, reporting something like:

> Refused to load the script 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' 'unsafe-eval' …

**Comment by lunethefirst** [comment]
Hey, thanks for this reply, I'll try again with what your example.  (=

**Comment by assiless** [comment]
> 1. What page (URL) did you visit?
> 
>     2. Can you show me the rule you tried?
> 
> 
> Here's the rule I tried:
> 
> ```js
> [
>     ["https://steampowered\\.com", [
>        ["script-src", "script-src https://cdn.jsdelivr.net"]
>     ]]
> ]
> ```
> 
> Then, I visited https://steampowered.com in Chromium, hit Ctrl+Shift+J, and pasted this:
> 
> ```js
> var script = document.createElement("script");
> script.src = "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js";
> document.documentElement.appendChild(script);
> ```
> 
> And no errors appeared. In contrast, if I remove the rule, the script would fail to load, reporting something like:
> 
> > Refused to load the script 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' 'unsafe-eval' …

Does this still work?
My template wouldn't work for Twitter, so I tested your sample and got the following
```
Refused to load the script 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://store.cloudflare.steamstatic.com/ https://store.cloudflare.steamstatic.com/ *.google-analytics.com https://www.gstatic.com https://recaptcha.net https://www.gstatic.cn/recaptcha/ https://www.youtube.com/ https://s.ytimg.com". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```
